# Generated by Django 5.2.17 on 2026-09-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oversight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingnote',
            name='kind',
            field=models.CharField(choices=[('change_requested', 'Change requested'), ('archived', 'Archived'), ('restored', 'Put back in the shop')], max_length=20),
        ),
    ]
