# Generated by Django 5.2.17 on 2026-09-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productimage_credit_productimage_credit_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField()),
                ('sku_id', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_minor', models.BigIntegerField()),
                ('line_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='catalog.artisanprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='catalog.product')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['artisan', '-occurred_at'], name='sales_artisan_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_id', 'sku_id'), name='one_sale_line_per_sku_per_order')],
            },
        ),
    ]
