# Generated by Django 5.2.17 on 2026-09-22 20:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('name_bn', models.CharField(blank=True, help_text='Name in Bangla', max_length=80)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('home_division', models.CharField(blank=True, choices=[('barishal', 'Barishal'), ('chattogram', 'Chattogram'), ('dhaka', 'Dhaka'), ('khulna', 'Khulna'), ('mymensingh', 'Mymensingh'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('sylhet', 'Sylhet')], max_length=16)),
                ('home_district', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'catalog_craft',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('story', models.TextField(blank=True, help_text='How they learned the craft')),
                ('division', models.CharField(choices=[('barishal', 'Barishal'), ('chattogram', 'Chattogram'), ('dhaka', 'Dhaka'), ('khulna', 'Khulna'), ('mymensingh', 'Mymensingh'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('sylhet', 'Sylhet')], max_length=16)),
                ('district', models.CharField(max_length=60)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL)),
                ('crafts', models.ManyToManyField(blank=True, related_name='artisans', to='catalog.craft')),
            ],
            options={
                'db_table': 'catalog_artisan_profile',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('materials', models.CharField(blank=True, max_length=200)),
                ('dimensions', models.CharField(blank=True, max_length=120)),
                ('origin_district', models.CharField(blank=True, max_length=60)),
                ('price_minor', models.PositiveIntegerField(help_text="Price in the currency's minor unit")),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('stock', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_days', models.PositiveSmallIntegerField(default=3, help_text='Before it ships', validators=[django.core.validators.MaxValueValidator(365)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.artisanprofile')),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.craft')),
            ],
            options={
                'db_table': 'catalog_product',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_image',
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-created_at'], name='catalog_pro_status_c865a0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['craft', 'status'], name='catalog_pro_craft_i_ef17a4_idx'),
        ),
    ]
