# Generated by Django 5.2.17 on 2026-09-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='credit',
            field=models.CharField(blank=True, help_text='Photographer or source', max_length=120),
        ),
        migrations.AddField(
            model_name='productimage',
            name='credit_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productimage',
            name='license',
            field=models.CharField(blank=True, help_text='e.g. "CC BY-SA 4.0"', max_length=40),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(max_length=700),
        ),
    ]
