# Generated by Django 5.2.17 on 2026-09-23 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage_credit_productimage_credit_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_favourite',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='favourite_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'product'), name='one_favourite_per_piece')],
            },
        ),
    ]
