apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: poshra

resources:
  - namespace.yaml
  - buckets-job.yaml
  - loki.yaml
  - tempo.yaml
  - prometheus.yaml
  - otel-collector.yaml
  - grafana.yaml
