apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Local 3-node cluster (1 control plane + 2 workers) on 192.168.110.0/24.
resources:
  - ../../base

# CI replaces these tags with the built commit SHA:
#   sed -i "s|newTag: 11ffeae5b4975cccd74342aa19e1de0dbf88e3d5
images:
  - name: ghcr.io/tarunno/poshra/marketplace
    newTag: 11ffeae5b4975cccd74342aa19e1de0dbf88e3d5
  - name: ghcr.io/tarunno/poshra/web
    newTag: 11ffeae5b4975cccd74342aa19e1de0dbf88e3d5
  - name: ghcr.io/tarunno/poshra/kong
    newTag: 11ffeae5b4975cccd74342aa19e1de0dbf88e3d5
