apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Local 3-node cluster (1 control plane + 2 workers) on 192.168.110.0/24.
resources:
  - ../../base

# CI replaces these tags with the built commit SHA:
#   sed -i "s|newTag: 644f1af39efe9c5a5e9421b6685271988c7d9fde
images:
  - name: ghcr.io/tarunno/poshra/marketplace
    newTag: 644f1af39efe9c5a5e9421b6685271988c7d9fde
  - name: ghcr.io/tarunno/poshra/web
    newTag: 644f1af39efe9c5a5e9421b6685271988c7d9fde
  - name: ghcr.io/tarunno/poshra/kong
    newTag: 644f1af39efe9c5a5e9421b6685271988c7d9fde
