apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Local 3-node cluster (1 control plane + 2 workers) on 192.168.110.0/24.
resources:
  - ../../base

# CI replaces these tags with the built commit SHA:
#   sed -i "s|newTag: eb8d6fd1f0b71cc9d9d59e9e4e07aae6d4714199
images:
  - name: ghcr.io/tarunno/poshra/marketplace
    newTag: eb8d6fd1f0b71cc9d9d59e9e4e07aae6d4714199
  - name: ghcr.io/tarunno/poshra/web
    newTag: eb8d6fd1f0b71cc9d9d59e9e4e07aae6d4714199
  - name: ghcr.io/tarunno/poshra/kong
    newTag: eb8d6fd1f0b71cc9d9d59e9e4e07aae6d4714199
